modLoader = "javafml"
loaderVersion = "[47,)"
license = "All rights reserved"
issueTrackerURL="https://github.com/Evoslab/Candycraft-Rebaked/issues"

[[mods]]
    modId="candycraft_rebaked"
    version="${file.jarVersion}"
    displayName="Candycraft-Rebaked"
    displayURL="https://github.com/Evoslab/Candycraft-Rebaked"
    logoFile="candy_creeper_head.png"
    credits="Some peeps who like minecraft and sweets"
    authors="Team Treats"
    description="We really like sugar."

[[dependencies.candycraft_rebaked]]
    modId="forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
    side="BOTH"

[[dependencies.candycraft_rebaked]]
    modId="minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
    side="BOTH"

[[dependencies.candycraft_rebaked]]
    modId="blueprint"
mandatory = true
versionRange = "[7.0.0,)"
ordering = "AFTER"
    side="BOTH"

