modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Evoslab/Candycraft-Rebaked/issues"

[[mods]]
    modId="candycraft_rebaked"
    version="${file.jarVersion}"
    displayName="Candycraft-Rebaked"
    displayURL="https://github.com/Evoslab/Candycraft-Rebaked"
    logoFile="candy_creeper_head.png"
    credits="Some peeps who like minecraft and sweets"
    authors="Team Treats"
    description="We really like sugar."

[[dependencies.candycraft_rebaked]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.candycraft_rebaked]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.candycraft_rebaked]]
    modId="blueprint"
    mandatory=true
    versionRange="[x.x.x,)"
    ordering="AFTER"
    side="BOTH"

